spring:
  application:
    name: service-b

server:
  port: 8811 #${PORT:${SERVER_PORT:0}} 随机指定个没使用的端口

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8010/eureka/ #eureka服务注册地址